# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.07) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory

#
# Generated from /tmp/sdoP4iLTHM/northamerica.  Olson data version 2015a
#
# Do not edit this file directly.
#
package DateTime::TimeZone::America::Cayman;
$DateTime::TimeZone::America::Cayman::VERSION = '1.85';
use strict;

use Class::Singleton 1.03;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::America::Cayman::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
    [
DateTime::TimeZone::NEG_INFINITY, #    utc_start
59611181132, #      utc_end 1890-01-01 05:25:32 (Wed)
DateTime::TimeZone::NEG_INFINITY, #  local_start
59611161600, #    local_end 1890-01-01 00:00:00 (Wed)
-19532,
0,
'LMT',
    ],
    [
59611181132, #    utc_start 1890-01-01 05:25:32 (Wed)
60307996031, #      utc_end 1912-02-01 05:07:11 (Thu)
59611162701, #  local_start 1890-01-01 00:18:21 (Wed)
60307977600, #    local_end 1912-02-01 00:00:00 (Thu)
-18431,
0,
'KMT',
    ],
    [
60307996031, #    utc_start 1912-02-01 05:07:11 (Thu)
DateTime::TimeZone::INFINITY, #      utc_end
60307978031, #  local_start 1912-02-01 00:07:11 (Thu)
DateTime::TimeZone::INFINITY, #    local_end
-18000,
0,
'EST',
    ],
];

sub olson_version {'2015a'}

sub has_dst_changes {0}

sub _max_year {2025}

sub _new_instance {
    return shift->_init( @_, spans => $spans );
}



1;

